# Generated by Django 5.1.3 on 2024-11-22 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.TextField(help_text='Enter the quote text here.')),
                ('verse_ref', models.CharField(help_text='Enter the reference (chapter:verse) for the quote.', max_length=55)),
                ('holy_book', models.CharField(help_text='Specify the name of the holy book.', max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the quote was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time whn the quote was lst update.')),
                ('user', models.ForeignKey(help_text='User who added the quote.', on_delete=django.db.models.deletion.CASCADE, related_name='quote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
